default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vocabl_development

test:
  <<: *default
  database: vocabl_test

production:
  <<: *default
  database: vocabl_production
  username: username
  password: <%= ENV['PROJECT_DATABASE_PASSWORD'] %>
